trigger:
  branches:
    include:
    # These are the branches we'll mirror to our internal ADO instance
    # Keep this set limited as appropriate (don't mirror individual user branches).
    - main

schedules:
# Build weekly to ensure the pipeline isn't deactivated.
- cron: "0 10 1/7 * *"
  displayName: Weekly sync
  branches:
    include:
    - dev
  always: true

resources:
  repositories:
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/cfs.yml@eng

extends:
  template: ci/code-mirror.yml@eng
