# This is our package-publishing pipeline.
# When executed, it automatically publishes the output of the 'official pipeline' (the nupkgs) to our internal ADO feed.
# It may optionally also publish the packages to NuGet, but that is gated behind a manual approval.

trigger: none # only trigger is manual
pr: none # only trigger is manual

# We include to this variable group to be able to access the NuGet API key
variables:
- group: durabletask_config

resources:
    repositories:
        - repository: 1es
          type: git
          name: 1ESPipelineTemplates/1ESPipelineTemplates
          ref: refs/tags/release
        - repository: eng
          type: git
          name: engineering
          ref: refs/tags/release

    pipelines:
    - pipeline: officialPipeline # Reference to the pipeline to be used as an artifact source
      source: 'durabletask-netherite.official'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
        name: 1es-pool-azfunc
        image: 1es-windows-2022
        os: windows

    stages:
    - stage: release
      jobs:

      # ADO release
      - job: adoRelease
        displayName: ADO Release
        templateContext:
          inputs:
          - input: pipelineArtifact
            pipeline: officialPipeline  # Pipeline reference, as defined in the resources section
            artifactName: drop
            targetPath: $(System.DefaultWorkingDirectory)/drop

          # The preferred method of release on 1ES is by populating the 'output' section of a 1ES template.
          # We use this method to release to ADO, but not to release to NuGet; this is explained in the 'nugetRelease' job.
          # To read more about the 'output syntax', see: 
          # - https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/outputs
          # - https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/outputs/nuget-packages
          outputs:
          - output: nuget # 'nuget' is an output "type" for pushing to NuGet
            displayName: 'Push to durabletask ADO feed'
            packageParentPath: $(System.DefaultWorkingDirectory) # This needs to be set to some prefix of the `packagesToPush` parameter. Apparently it helps with SDL tooling
            packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg;!$(System.DefaultWorkingDirectory)/**/*.symbols.nupkg'
            publishVstsFeed: '3f99e810-c336-441f-8892-84983093ad7f/c895696b-ce37-4fe7-b7ce-74333a04f8bf'
            allowPackageConflicts: true

      # NuGet approval gate
      - job: nugetApproval
        displayName: NuGetApproval
        pool: server # This task only works when executed on serverl pools, so this needs to be specified
        steps:
          # Wait for manual approval. 
          - task: ManualValidation@1
            inputs:
              instructions: Confirm you want to push to NuGet
              onTimeout: 'reject'

      # NuGet release (Microsoft.Azure.DurableTask.Netherite)
      - job: nugetRelease_Microsoft_Azure_DurableTask_Netherite
        displayName: NuGet Release (Microsoft.Azure.DurableTask.Netherite)
        dependsOn: nugetApproval
        condition: succeeded('nugetApproval') # nuget packages need to be on ADO first
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            pipeline: officialPipeline  # Pipeline reference as defined in the resources section
            artifactName: drop
            targetPath: $(System.DefaultWorkingDirectory)/drop
        steps:
        - task: 1ES.PublishNuget@1
          displayName: 'NuGet push (Microsoft.Azure.DurableTask.Netherite)'
          inputs:
            command: push
            nuGetFeedType: external
            publishFeedCredentials: 'DurableTask org NuGet API Key'
            packagesToPush: '$(System.DefaultWorkingDirectory)/drop/Microsoft.Azure.DurableTask.Netherite.*.nupkg;!$(System.DefaultWorkingDirectory)/drop/Microsoft.Azure.DurableTask.Netherite.AzureFunctions.*.nupkg;!$(System.DefaultWorkingDirectory)/**/*.symbols.nupkg' # Excludes Microsoft.Azure.DurableTask.Netherite.AzureFunctions.nupkg
            packageParentPath: $(System.DefaultWorkingDirectory) # This needs to be set to some prefix of the `packagesToPush` parameter. Apparently it helps with SDL tooling

      # NuGet release (Microsoft.Azure.DurableTask.Netherite.AzureFunctions)
      - job: nugetRelease_Microsoft_Azure_DurableTask_Netherite_AzureFunctions
        displayName: NuGet Release (Microsoft.Azure.DurableTask.Netherite.AzureFunctions)
        dependsOn: nugetApproval
        condition: succeeded('nugetApproval') # nuget packages need to be on ADO first
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            pipeline: officialPipeline  # Pipeline reference as defined in the resources section
            artifactName: drop
            targetPath: $(System.DefaultWorkingDirectory)/drop
        steps:
        - task: 1ES.PublishNuget@1
          displayName: 'NuGet push (Microsoft.Azure.DurableTask.Netherite.AzureFunctions)'
          inputs:
            command: push
            nuGetFeedType: external
            publishFeedCredentials: 'DurableTask org NuGet API Key'
            packagesToPush: '$(System.DefaultWorkingDirectory)/drop/Microsoft.Azure.DurableTask.Netherite.AzureFunctions.*.nupkg;!$(System.DefaultWorkingDirectory)/**/*.symbols.nupkg' # Despite this being a custom command, we need to keep this for 1ES validation
            packageParentPath: $(System.DefaultWorkingDirectory) # This needs to be set to some prefix of the `packagesToPush` parameter. Apparently it helps with SDL tooling


      # NuGet release (Microsoft.Azure.Functions.Worker.Extensions.DurableTask.Netherite)
      - job: nugetRelease_Microsoft_Azure_Functions_Worker_Extensions_DurableTask_Netherite
        displayName: NuGet Release (Microsoft.Azure.Functions.Worker.Extensions.DurableTask.Netherite)
        dependsOn: nugetApproval
        condition: succeeded('nugetApproval') # nuget packages need to be on ADO first
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            pipeline: officialPipeline  # Pipeline reference as defined in the resources section
            artifactName: drop
            targetPath: $(System.DefaultWorkingDirectory)/drop
        steps:
        - task: 1ES.PublishNuget@1
          displayName: 'NuGet push (Microsoft.Azure.Functions.Worker.Extensions.DurableTask.Netherite)'
          inputs:
            command: push
            nuGetFeedType: external
            publishFeedCredentials: 'DurableTask org NuGet API Key'
            packagesToPush: '$(System.DefaultWorkingDirectory)/drop/Microsoft.Azure.Functions.Worker.Extensions.DurableTask.Netherite.*.nupkg;!$(System.DefaultWorkingDirectory)/**/*.symbols.nupkg' # Despite this being a custom command, we need to keep this for 1ES validation
            packageParentPath: $(System.DefaultWorkingDirectory) # This needs to be set to some prefix of the `packagesToPush` parameter. Apparently it helps with SDL tooling
