//  ----------------------------------------------------------------------------------
//  Copyright Microsoft Corporation. All rights reserved.
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  http://www.apache.org/licenses/LICENSE-2.0
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//  ----------------------------------------------------------------------------------

namespace DurableTask.Netherite
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Text;
    using DurableTask.Core;

    class ActivityWorkItem : TaskActivityWorkItem
    {
        public Partition Partition { get; set; }

        // the partition for the orchestration that issued this activity
        public uint OriginPartition { get; set; }

        // a partition-local identifier for this activity (is a sequence number generated by ActivitiesState)
        public long ActivityId { get; set; }

        public ActivityWorkItem(Partition partition, long activityId, TaskMessage message)
        {
            this.Partition = partition;
            this.OriginPartition = partition.PartitionFunction(message.OrchestrationInstance.InstanceId);
            this.ActivityId = activityId;
            this.Id = activityId.ToString();
            this.LockedUntilUtc = DateTime.MaxValue; // this backend does not require workitem lock renewals
            this.TaskMessage = message;
        }

        public string WorkItemId => $"A{this.ActivityId}";
    }
}
